apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.nameSpace }}
  labels:
    main-app: {{ .Values.mainAppName }}
    app: {{ .Values.appName }}
  annotations:
    mcm.ibm.com/service-discovery: "{}"
spec:
  type: ClusterIP
  ports:
    - name: my-http
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.serviceTargetPort }}
  selector:
    main-app: {{ .Values.mainAppName }}
    app: {{ .Values.appName }}
  