apiVersion: v1
kind: Service
metadata:
  name: gstore-sales
  labels:
    app: gstore-application
spec:
  type: ClusterIP
  ports:
    - name: my-http
      port: 9030
      targetPort: 9030
  selector:
    app: gstore-application
