apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gstore-sales
  labels:
    app: gstore-application
spec:
  path: /
  to:
    kind: Service
    name: gstore-sales
    weight: 100
  port:
    targetPort: my-http