apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: gstore-helm-application
  namespace: gstore-helm-subscription-ns
  labels:
    mcmapp: gstore-helm
spec:
  componentKinds:
    - group: app.ibm.com
      kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      mcmapp: gstore-helm
