apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: gan1-application
  namespace: gan1-subscription-ns
  labels:
    app-label: gan1
spec:
  componentKinds:
    - group: app.ibm.com
      kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      app-label: gan1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gan1-skip-cert-verify
  namespace: gan1-channel-ns
  labels:
    app-label: gan1
data:
  insecureSkipVerify: "true"
---
apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: gan1-channel
  namespace: gan1-channel-ns
  labels:
    app-label: gan1
spec:
  type: HelmRepo
  #Type1: pathname: https://github.com/GandhiCloudLab/mcm-helm-sample.git
  #Type2: pathname: https://github.com/GandhiCloudLab/mcm-helm-sample/tree/master/charts
  pathname: https://raw.githubusercontent.com/GandhiCloudLab/mcm-helm-sample/tree/master/charts
  #Type4:  pathname: https://raw.githubusercontent.com/GandhiCloudLab/mcm-helm-sample/tree/master/tgz
  #Type5: pathname: https://github.com/GandhiCloudLab/mcm-helm-sample/tree/master/tgz
  #Type6: pathname:  https://github.com/GandhiCloudLab/mcm-helm-sample.git
  configMapRef:
    name: gan1-skip-cert-verify
    kind: ConfigMap
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: gan1-placementrule
  namespace: gan1-subscription-ns
  labels:
    app-label: gan1
spec: 
  clusterReplicas: 2
  clusterLabels:
    matchExpressions:
      - key: cloud
        operator: In
        values:
          - IBM
---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: gan1-subscription
  namespace: gan1-subscription-ns
  labels:
    app-label: gan1
spec:
  channel: gan1-channel-ns/gan1-channel
  source: https://raw.githubusercontent.com/GandhiCloudLab/mcm-helm-sample/tree/master/charts
  #Type1: name: charts/gstore-sales
  #Type2: name: gstore-sales
  #Type3: name: gstore-sales
  #Type4: name: gstore-sales
  name: gstore-sales
   #Type6: name: tgz/gstore-sales
  packageFilter:
    version: "0.1.0"
  placement:
    placementRef: 
      name: gan1-placementrule
      kind: PlacementRule
      apiVersion: app.ibm.com/v1alpha1
  overrides:
    - clusterName: "/"
      clusterOverrides:
      - path: "metadata.namespace"
        value: gan1-app-ns
---
